# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:
  docs:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: sh -c "export CYPRESS_CACHE_FOLDER=/docs/packages/docs/.cache && npm i && npm run generate:components && npm run watch"
    ports:
      - '3000:3000'
    volumes:
      - .:/docs:z
      - /docs/packages/docs/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 180s
